### ISSUE TITLE
Update license (first-timers-only)

### ISSUE THREAD

**Issue by TalAter** [DAVFoundation/captain-sky#1]
## first-timers-only

This issue is tagged :octocat: **first-timers-only**. It is only for people who have never contributed to open source before, and are looking for an easy way take their first steps.

Consider this your chance to dip your toe into the world of open-source, and get some bragging rights for helping make drones fly, cars find charging stations, and people and goods get from place to place.

Find more **first-timers-only** issues [here](https://github.com/issues?utf8=%E2%9C%93&q=is%3Aopen+is%3Aissue+archived%3Afalse+label%3A%22good+first+issue%22+user%3ADAVFoundation+).

Thank you for your help :heart:

## What is this project? 

DAV (Decentralized Autonomous Vehicles) is a non-profit foundation working to build an open-source infrastructure for autonomous vehicles (cars, drones, trucks, robots, boats, and all the service providers around them) to communicate and transact with each other over blockchain.

As an organization that believes in building a large community of open-source contributors, we often create issues like this one to help people take their first few steps into the world of open source.

### Captain Sky

The DAV project you are looking at is Captain Sky. It is a connector between drone charging stations, the DAV network, and drones looking for charging.

## How you can help

This project is open sourced under an MIT license, but the `/src/sky-dashbaord/package.json` file accidentally lists the license as `'ISC'`.

Change it to `'MIT'`.

### Contributing to Captain Sky

- [ ] Make sure this issue is labeled up-for-grabs and not labeled claimed, to verify no one else is working on it.
- [ ] Comment in this issue that you would like to do it.
- [ ] Open the [Captain Sky GitHub page](https://github.com/DAVFoundation/captain-sky) and click the ★ Star and then ⑂ Fork buttons.
- [ ] Clone a copy to your local machine with `$ git clone git@github.com:YOUR-GITHUB-USER-NAME/captain-sky.git`
- [ ] **Code! Code! Code!**
- [ ] Commit your changes and push your local changes back to github with `$ git push -u origin master`
- [ ] Visit your fork on GitHub.com ([https://github.com/YOUR-USER-NAME/captain-sky](https://github.com/YOUR-USER-NAME/captain-sky)) and create a pull request for your changes.
- [ ] Make sure your pull request describes exactly what you changed and references this issue (include the issue number in the title like this: `#1`)
- [ ] Please do not fix more than one issue at a time. Your pull request should only fix what is described in this issue.

### Asking for help

We appreciate your effort in taking the time to work on this issue and help out the open source community and the foundation. If you need any help, feel free to ask below or in our [gitter channel](https://gitter.im/DAVFoundation/DAV-Contributors). We are always happy to help 😄

We sometimes feature the work done by the community on our website. If you would like your GitHub user excluded from that, please email tal@dav.network

**Comment by mariolo1985** [comment]
Hi - I would like to help with this issue :)

**Comment by TalAter** [comment]
Thank you @mariolo1985 !
Please, go ahead 👍

**Comment by mariolo1985** [comment]
Hello,

PR has been submitted. Thank you for allowing me to contribute.

**Comment by mariolo1985** [comment]
Whoops, I forgot to add you as a reviewer.

**Comment by TalAter** [comment]
Nice! Merged. 🎆 

Thank you so much, and hope to see more contributions from you to the open source community. We have plenty of issues open https://github.com/issues?utf8=%E2%9C%93&q=is%3Aopen+is%3Aissue+archived%3Afalse+label%3A%22good+first+issue%22+user%3ADAVFoundation+

I also hope SLC has cooled down a bit. It was scorching when I was there a month and a half ago.

**Comment by mariolo1985** [comment]
Thanks again for allowing me to contribute @TalAter! I will keep an eye on the issues within the DAVFoundation org :)

Believe it or not, it is still pretty brutal during the day but night time temperatures has been great. Let me know if you need some recommendations when you are in SLC next!
